/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import javax.swing.ImageIcon;

/**
 *
 * @author multi
 */
public class ViewCalcluadora extends javax.swing.JFrame {

    /**
     * Creates new form ViewCalcluadora
     */
    double answer;
    double result;
    public ViewCalcluadora() {
        initComponents();
        this.setIconImage(new ImageIcon("src/Imagens/Icon Calculadora.png").getImage());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelButton = new javax.swing.JPanel();
        panelMain = new javax.swing.JPanel();
        panelScreen = new javax.swing.JPanel();
        tfScreen = new javax.swing.JTextField();
        panelButtons = new javax.swing.JPanel();
        buttonSeven = new javax.swing.JButton();
        buttonSplit = new javax.swing.JButton();
        buttonC = new javax.swing.JButton();
        buttonDEL = new javax.swing.JButton();
        buttonEight = new javax.swing.JButton();
        buttonNine1 = new javax.swing.JButton();
        buttonFatorial = new javax.swing.JButton();
        buttonExp = new javax.swing.JButton();
        buttonRoot = new javax.swing.JButton();
        buttonMulti = new javax.swing.JButton();
        buttonFour = new javax.swing.JButton();
        buttonFive = new javax.swing.JButton();
        buttonSix = new javax.swing.JButton();
        buttonAdd = new javax.swing.JButton();
        buttonOne = new javax.swing.JButton();
        buttonTwo = new javax.swing.JButton();
        buttonTree = new javax.swing.JButton();
        buttonSubtract = new javax.swing.JButton();
        buttonPoint = new javax.swing.JButton();
        buttonZero1 = new javax.swing.JButton();
        buttonAnswer = new javax.swing.JButton();
        buttonEqual = new javax.swing.JButton();

        panelButton.setBackground(new java.awt.Color(51, 204, 255));

        javax.swing.GroupLayout panelButtonLayout = new javax.swing.GroupLayout(panelButton);
        panelButton.setLayout(panelButtonLayout);
        panelButtonLayout.setHorizontalGroup(
            panelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelButtonLayout.setVerticalGroup(
            panelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 316, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 204, 255));
        setForeground(new java.awt.Color(51, 204, 255));

        panelMain.setBackground(new java.awt.Color(51, 204, 255));

        panelScreen.setBackground(new java.awt.Color(51, 204, 255));

        tfScreen.setBackground(new java.awt.Color(255, 255, 255));
        tfScreen.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        tfScreen.setForeground(new java.awt.Color(0, 0, 0));
        tfScreen.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout panelScreenLayout = new javax.swing.GroupLayout(panelScreen);
        panelScreen.setLayout(panelScreenLayout);
        panelScreenLayout.setHorizontalGroup(
            panelScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelScreenLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(tfScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        panelScreenLayout.setVerticalGroup(
            panelScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelScreenLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(tfScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        panelButtons.setBackground(new java.awt.Color(51, 204, 255));

        buttonSeven.setBackground(new java.awt.Color(0, 0, 0));
        buttonSeven.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        buttonSeven.setForeground(new java.awt.Color(255, 255, 255));
        buttonSeven.setText("7");
        buttonSeven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSevenActionPerformed(evt);
            }
        });

        buttonSplit.setBackground(new java.awt.Color(255, 102, 0));
        buttonSplit.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        buttonSplit.setForeground(new java.awt.Color(255, 255, 255));
        buttonSplit.setText("÷");

        buttonC.setBackground(new java.awt.Color(255, 51, 51));
        buttonC.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        buttonC.setForeground(new java.awt.Color(255, 255, 255));
        buttonC.setText("C");
        buttonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCActionPerformed(evt);
            }
        });

        buttonDEL.setBackground(new java.awt.Color(153, 153, 153));
        buttonDEL.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        buttonDEL.setForeground(new java.awt.Color(255, 255, 255));
        buttonDEL.setText("DEL");
        buttonDEL.setPreferredSize(new java.awt.Dimension(75, 40));
        buttonDEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDELActionPerformed(evt);
            }
        });

        buttonEight.setBackground(new java.awt.Color(0, 0, 0));
        buttonEight.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        buttonEight.setForeground(new java.awt.Color(255, 255, 255));
        buttonEight.setText("8");
        buttonEight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEightActionPerformed(evt);
            }
        });

        buttonNine1.setBackground(new java.awt.Color(0, 0, 0));
        buttonNine1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        buttonNine1.setForeground(new java.awt.Color(255, 255, 255));
        buttonNine1.setText("9");
        buttonNine1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNine1ActionPerformed(evt);
            }
        });

        buttonFatorial.setBackground(new java.awt.Color(0, 0, 0));
        buttonFatorial.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        buttonFatorial.setForeground(new java.awt.Color(255, 255, 255));
        buttonFatorial.setText("x!");

        buttonExp.setBackground(new java.awt.Color(0, 0, 0));
        buttonExp.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        buttonExp.setForeground(new java.awt.Color(255, 255, 255));
        buttonExp.setText("x^2");

        buttonRoot.setBackground(new java.awt.Color(0, 0, 0));
        buttonRoot.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        buttonRoot.setForeground(new java.awt.Color(255, 255, 255));
        buttonRoot.setText("√x");

        buttonMulti.setBackground(new java.awt.Color(255, 102, 0));
        buttonMulti.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        buttonMulti.setForeground(new java.awt.Color(255, 255, 255));
        buttonMulti.setText("×");

        buttonFour.setBackground(new java.awt.Color(0, 0, 0));
        buttonFour.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        buttonFour.setForeground(new java.awt.Color(255, 255, 255));
        buttonFour.setText("4");
        buttonFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFourActionPerformed(evt);
            }
        });

        buttonFive.setBackground(new java.awt.Color(0, 0, 0));
        buttonFive.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        buttonFive.setForeground(new java.awt.Color(255, 255, 255));
        buttonFive.setText("5");
        buttonFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFiveActionPerformed(evt);
            }
        });

        buttonSix.setBackground(new java.awt.Color(0, 0, 0));
        buttonSix.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        buttonSix.setForeground(new java.awt.Color(255, 255, 255));
        buttonSix.setText("6");
        buttonSix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSixActionPerformed(evt);
            }
        });

        buttonAdd.setBackground(new java.awt.Color(255, 102, 0));
        buttonAdd.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        buttonAdd.setForeground(new java.awt.Color(255, 255, 255));
        buttonAdd.setText("+");
        buttonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddActionPerformed(evt);
            }
        });

        buttonOne.setBackground(new java.awt.Color(0, 0, 0));
        buttonOne.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        buttonOne.setForeground(new java.awt.Color(255, 255, 255));
        buttonOne.setText("1");
        buttonOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOneActionPerformed(evt);
            }
        });

        buttonTwo.setBackground(new java.awt.Color(0, 0, 0));
        buttonTwo.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        buttonTwo.setForeground(new java.awt.Color(255, 255, 255));
        buttonTwo.setText("2");
        buttonTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTwoActionPerformed(evt);
            }
        });

        buttonTree.setBackground(new java.awt.Color(0, 0, 0));
        buttonTree.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        buttonTree.setForeground(new java.awt.Color(255, 255, 255));
        buttonTree.setText("3");
        buttonTree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTreeActionPerformed(evt);
            }
        });

        buttonSubtract.setBackground(new java.awt.Color(255, 102, 0));
        buttonSubtract.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        buttonSubtract.setForeground(new java.awt.Color(255, 255, 255));
        buttonSubtract.setText("-");
        buttonSubtract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSubtractActionPerformed(evt);
            }
        });

        buttonPoint.setBackground(new java.awt.Color(0, 0, 0));
        buttonPoint.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        buttonPoint.setForeground(new java.awt.Color(255, 255, 255));
        buttonPoint.setText(".");
        buttonPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPointActionPerformed(evt);
            }
        });

        buttonZero1.setBackground(new java.awt.Color(0, 0, 0));
        buttonZero1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        buttonZero1.setForeground(new java.awt.Color(255, 255, 255));
        buttonZero1.setText("0");
        buttonZero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonZero1ActionPerformed(evt);
            }
        });

        buttonAnswer.setBackground(new java.awt.Color(0, 0, 0));
        buttonAnswer.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        buttonAnswer.setForeground(new java.awt.Color(255, 255, 255));
        buttonAnswer.setText("Ans");
        buttonAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAnswerActionPerformed(evt);
            }
        });

        buttonEqual.setBackground(new java.awt.Color(0, 153, 51));
        buttonEqual.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        buttonEqual.setForeground(new java.awt.Color(255, 255, 255));
        buttonEqual.setText("=");

        javax.swing.GroupLayout panelButtonsLayout = new javax.swing.GroupLayout(panelButtons);
        panelButtons.setLayout(panelButtonsLayout);
        panelButtonsLayout.setHorizontalGroup(
            panelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelButtonsLayout.createSequentialGroup()
                        .addComponent(buttonRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonExp, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelButtonsLayout.createSequentialGroup()
                                .addComponent(buttonC, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buttonDEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelButtonsLayout.createSequentialGroup()
                                .addComponent(buttonFatorial, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buttonSplit, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelButtonsLayout.createSequentialGroup()
                        .addComponent(buttonSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonEight, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonNine1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonMulti, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelButtonsLayout.createSequentialGroup()
                        .addComponent(buttonFour, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonFive, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonSix, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonSubtract, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelButtonsLayout.createSequentialGroup()
                        .addComponent(buttonOne, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonTree, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelButtonsLayout.createSequentialGroup()
                        .addComponent(buttonZero1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelButtonsLayout.setVerticalGroup(
            panelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelButtonsLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonC, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonDEL, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonExp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonFatorial, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSplit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonEight, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonNine1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonMulti, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonFour, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonFive, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSix, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSubtract, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonTree, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonOne, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonZero1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelScreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addComponent(panelScreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonAddActionPerformed

    private void buttonSubtractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSubtractActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSubtractActionPerformed

    private void buttonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCActionPerformed
        cleanScreen();

    }//GEN-LAST:event_buttonCActionPerformed

    private void buttonDELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDELActionPerformed
        deleteCharacter();
    }//GEN-LAST:event_buttonDELActionPerformed

    private void buttonZero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonZero1ActionPerformed
       tfScreen.setText(tfScreen.getText()+0);
    }//GEN-LAST:event_buttonZero1ActionPerformed

    private void buttonPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPointActionPerformed
             tfScreen.setText(tfScreen.getText()+".");
    }//GEN-LAST:event_buttonPointActionPerformed

    private void buttonAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAnswerActionPerformed
             tfScreen.setText(tfScreen.getText()+answer);
    }//GEN-LAST:event_buttonAnswerActionPerformed

    private void buttonOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOneActionPerformed
             tfScreen.setText(tfScreen.getText()+1);
    }//GEN-LAST:event_buttonOneActionPerformed

    private void buttonTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTwoActionPerformed
           tfScreen.setText(tfScreen.getText()+2);
    }//GEN-LAST:event_buttonTwoActionPerformed

    private void buttonTreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTreeActionPerformed
             tfScreen.setText(tfScreen.getText()+3);
    }//GEN-LAST:event_buttonTreeActionPerformed

    private void buttonFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFourActionPerformed
             tfScreen.setText(tfScreen.getText()+4);
    }//GEN-LAST:event_buttonFourActionPerformed

    private void buttonFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFiveActionPerformed
             tfScreen.setText(tfScreen.getText()+5);
    }//GEN-LAST:event_buttonFiveActionPerformed

    private void buttonSixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSixActionPerformed
            tfScreen.setText(tfScreen.getText()+6);
    }//GEN-LAST:event_buttonSixActionPerformed

    private void buttonSevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSevenActionPerformed
            tfScreen.setText(tfScreen.getText()+7);
    }//GEN-LAST:event_buttonSevenActionPerformed

    private void buttonEightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEightActionPerformed
            tfScreen.setText(tfScreen.getText()+8);
    }//GEN-LAST:event_buttonEightActionPerformed

    private void buttonNine1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNine1ActionPerformed
            tfScreen.setText(tfScreen.getText()+9);
    }//GEN-LAST:event_buttonNine1ActionPerformed

    private void cleanScreen() {
        tfScreen.setText("");
        requestFoco();
    }

    private void deleteCharacter() {
        if(tfScreen.getText().length()>0){
        int lenght = tfScreen.getText().length();
        String message = tfScreen.getText().substring(0, lenght - 1);
        tfScreen.setText(message);}
        requestFoco();
    }

    private void requestFoco(){
     if(tfScreen.getText().length()==0){
         tfScreen.requestFocus();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCalcluadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCalcluadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCalcluadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCalcluadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCalcluadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdd;
    private javax.swing.JButton buttonAnswer;
    private javax.swing.JButton buttonC;
    private javax.swing.JButton buttonDEL;
    private javax.swing.JButton buttonEight;
    private javax.swing.JButton buttonEqual;
    private javax.swing.JButton buttonExp;
    private javax.swing.JButton buttonFatorial;
    private javax.swing.JButton buttonFive;
    private javax.swing.JButton buttonFour;
    private javax.swing.JButton buttonMulti;
    private javax.swing.JButton buttonNine1;
    private javax.swing.JButton buttonOne;
    private javax.swing.JButton buttonPoint;
    private javax.swing.JButton buttonRoot;
    private javax.swing.JButton buttonSeven;
    private javax.swing.JButton buttonSix;
    private javax.swing.JButton buttonSplit;
    private javax.swing.JButton buttonSubtract;
    private javax.swing.JButton buttonTree;
    private javax.swing.JButton buttonTwo;
    private javax.swing.JButton buttonZero1;
    private javax.swing.JPanel panelButton;
    private javax.swing.JPanel panelButtons;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelScreen;
    private javax.swing.JTextField tfScreen;
    // End of variables declaration//GEN-END:variables
}
